<a href="https://colab.research.google.com/github/BhusareHarshad/Data_Scientist_Interview_Practise/blob/main/Pandas_Practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. **IMP** Concept - **Quick Comparison: `merge`, `join`, and `concat`**


| Feature | `pd.merge()` | `df.join()` | `pd.concat()` |
| :--- | :--- | :--- | :--- |
| **Logic** | **SQL-style** (Column-on-Column) | **Index-based** | 	Stacking along an axis |
| **Default Join** | `inner` | `left` | `outer` |
| **Primary Axis** | Horizontal (Columns) | Horizontal (Columns) | Vertical (Rows) or Horizontal |
| **Best For** | Relational data with shared IDs | Lookups where index is the key | Combining multiple similar CSVs |

---

### **Cheat Sheet Syntax**

#### **1. Merge (The Powerhouse)**
*Best for combining data based on specific column values.*
```python
# Inner join on a specific column
df_merged = pd.merge(df1, df2, on='id_column', how='inner')

In [ ]:
json_data = '''{
  "df_employees": [
    {"emp_id": 101, "name": "Alice", "dept_id": 1},
    {"emp_id": 102, "name": "Bob", "dept_id": 2},
    {"emp_id": 103, "name": "Charlie", "dept_id": 1},
    {"emp_id": 104, "name": "David", "dept_id": 3}
  ],
  "df_departments": [
    {"dept_id": 1, "dept_name": "HR"},
    {"dept_id": 2, "dept_name": "Engineering"},
    {"dept_id": 4, "dept_name": "Marketing"}
  ],
  "df_sales_q1": [
    {"emp_id": 101, "sales": 5000},
    {"emp_id": 102, "sales": 7000}
  ],
  "df_sales_q2": [
    {"emp_id": 101, "sales": 5500},
    {"emp_id": 103, "sales": 6000}
  ]
}'''

In [ ]:
import json

data = json.loads(json_data)

In [ ]:
df_employees = pd.DataFrame(data['df_employees'])
df_departments = pd.DataFrame(data['df_departments'])
df_sales_q1 = pd.DataFrame(data['df_sales_q1'])
df_sales_q2 = pd.DataFrame(data['df_sales_q2'])

In [ ]:
print(df_departments, '\n\n', df_employees)

   dept_id    dept_name
0        1           HR
1        2  Engineering
2        4    Marketing

    emp_id     name  dept_id
0     101    Alice        1
1     102      Bob        2
2     103  Charlie        1
3     104    David        3

In [ ]:
## Merge

df_emp_dep = pd.merge(df_departments, df_employees, on='dept_id', how='inner')

In [ ]:
df_emp_dep

   dept_id    dept_name  emp_id     name
0        1           HR     101    Alice
1        1           HR     103  Charlie
2        2  Engineering     102      Bob

In [ ]:
pd.concat()

In [ ]:
pd.concat([df_employees, df_departments], axis=1) ## Side by side

   emp_id     name  dept_id  dept_id    dept_name
0     101    Alice        1      1.0           HR
1     102      Bob        2      2.0  Engineering
2     103  Charlie        1      4.0    Marketing
3     104    David        3      NaN          NaN

In [ ]:
pd.concat([df_employees, df_departments], axis=0) # Stack rows

   emp_id     name  dept_id    dept_name
0   101.0    Alice        1          NaN
1   102.0      Bob        2          NaN
2   103.0  Charlie        1          NaN
3   104.0    David        3          NaN
0     NaN      NaN        1           HR
1     NaN      NaN        2  Engineering
2     NaN      NaN        4    Marketing

In [ ]:
## Kaggle datasets
!pip install kagglehub[pandas-datasets]

Requirement already satisfied: kagglehub[pandas-datasets] in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (4.67.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from kagglehub[pandas-datasets]) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->kagglehub[pandas-datasets]) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub[pandas-datasets]) (2026.2.25)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->kagglehub[pandas-datasets]) (1.17.0)

In [ ]:
# import kagglehub
# from kagglehub import KaggleDatasetAdapter

# file_path = "data.csv"

# df = kagglehub.load_dataset(
#   KaggleDatasetAdapter.PANDAS,
#   "thuandao/bank-transactions-dataset-for-fraud-detection",
#   file_path,
# )

# print("First 5 records:", df.head())

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/bank_transactions_data_2_augmented_clean_2.csv')

In [ ]:
df.head(5)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91
2,TX000003,AC00019,126.29,7/10/2023 18:16,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35
3,TX000004,AC00070,184.50,5/5/2023 16:32,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06
4,TX000005,AC00411,13.45,10/16/2023 17:51,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40

# 🐼 Pandas Essentials Cheat Sheet

### 📊 1. The Building Blocks
*   **DataFrame**: A 2-dimensional table (Rows & Columns).
*   **Series**: A 1-dimensional array. It is a single column extracted from a DataFrame.

---

### 📥 2. Loading Data

| Method | Description |
| :--- | :--- |
| `pd.read_csv('file.csv')` | Load data from a **CSV** file or URL. |
| `pd.read_excel('file.xlsx')` | Load data from an **Excel** spreadsheet. |

---

### 🔍 3. Inspecting the Data
Use these methods to get a "feel" for your dataset before cleaning it.

*   **`df.head()` / `df.tail()`**: View the first or last 5 rows of the data.
*   **`df.info()`**: Check data types, memory usage, and non-null counts.
*   **`df.describe()`**: Get summary statistics (Mean, Std Dev, Min/Max) for numerical columns.
*   **`df.shape`**: Returns a tuple `(rows, columns)` representing the size of the data.
*   **`df.columns` / `df.keys()`**: List all column names in the DataFrame.

---

### 🧹 4. Data Quality Checks and handling
*   **`df.isna().sum()`**: The "Gold Standard" for finding missing values. It counts how many `NaN` (null) values exist in each column.
*   `NaN` -  Not a number - used for float and int.
*   `None` - Missing `str` in non numeric value.
*   **`df.isnull().sum()`**

*   **`df.dropna`**
*   **`df.fillna`**
---

### 💡 Pro-Tip
> When using `df.describe()`, add the argument `include='all'` to see statistics for text-based (categorical) columns too!

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   TransactionID        50000 non-null  object
 1   AccountID            50000 non-null  object
 2   TransactionAmount    50000 non-null  float64
 3   TransactionDate      50000 non-null  object
 4   TransactionType      50000 non-null  object
 5   Location             50000 non-null  object
 6   DeviceID             50000 non-null  object
 7   IP Address           50000 non-null  object
 8   MerchantID           50000 non-null  object
 9   Channel              50000 non-null  object
 10  CustomerAge          50000 non-null  int64
 11  CustomerOccupation   50000 non-null  object
 12  TransactionDuration  50000 non-null  int64
 13  LoginAttempts        50000 non-null  int64
 14  AccountBalance       50000 non-null  float64
dtypes: float64(2), int64(3), object(10)
memory usage: 5.7+ MB

In [ ]:
df.describe()

,TransactionAmount,CustomerAge,TransactionDuration,LoginAttempts,AccountBalance
count,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000
mean,297.872214,44.647600,118.965320,1.12684,5122.738301
std,292.818888,17.800293,70.000681,0.60936,3904.266887
min,0.240000,18.000000,10.000000,1.00000,101.250000
25%,82.897500,27.000000,63.000000,1.00000,1508.720000
50%,209.355000,45.000000,111.000000,1.00000,4735.410000
75%,409.625000,59.000000,161.000000,1.00000,7713.670000
max,2060.590000,80.000000,300.000000,5.00000,14977.990000

In [ ]:
df.describe(include='all')

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
count,50000,50000,50000.000000,50000,50000,50000,50000,50000,50000,50000,50000.000000,50000,50000.000000,50000.00000,50000.000000
unique,50000,495,NaN,6373,2,43,681,592,100,3,NaN,4,NaN,NaN,NaN
top,TX049984,AC00363,NaN,6/12/2021,Debit,Fort Worth,D000548,200.136.146.93,M026,Branch,NaN,Student,NaN,NaN,NaN
freq,1,249,NaN,35,38747,1396,196,261,940,17278,NaN,13059,NaN,NaN,NaN
mean,NaN,NaN,297.872214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.647600,NaN,118.965320,1.12684,5122.738301
std,NaN,NaN,292.818888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.800293,NaN,70.000681,0.60936,3904.266887
min,NaN,NaN,0.240000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.000000,NaN,10.000000,1.00000,101.250000
25%,NaN,NaN,82.897500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,63.000000,1.00000,1508.720000
50%,NaN,NaN,209.355000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.000000,NaN,111.000000,1.00000,4735.410000
75%,NaN,NaN,409.625000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.000000,NaN,161.000000,1.00000,7713.670000
max,NaN,NaN,2060.590000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.000000,NaN,300.000000,5.00000,14977.990000

In [ ]:
df.shape

(50000, 15)

In [ ]:
df.columns

Index(['TransactionID', 'AccountID', 'TransactionAmount', 'TransactionDate',
       'TransactionType', 'Location', 'DeviceID', 'IP Address', 'MerchantID',
       'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration',
       'LoginAttempts', 'AccountBalance'],
      dtype='object')

In [ ]:
df.keys()

Index(['TransactionID', 'AccountID', 'TransactionAmount', 'TransactionDate',
       'TransactionType', 'Location', 'DeviceID', 'IP Address', 'MerchantID',
       'Channel', 'CustomerAge', 'CustomerOccupation', 'TransactionDuration',
       'LoginAttempts', 'AccountBalance'],
      dtype='object')

In [ ]:
df.isna().sum() ## NaN values

TransactionID          0
AccountID              0
TransactionAmount      0
TransactionDate        0
TransactionType        0
Location               0
DeviceID               0
IP Address             0
MerchantID             0
Channel                0
CustomerAge            0
CustomerOccupation     0
TransactionDuration    0
LoginAttempts          0
AccountBalance         0
dtype: int64

In [ ]:
df.isnull().sum()

TransactionID          0
AccountID              0
TransactionAmount      0
TransactionDate        0
TransactionType        0
Location               0
DeviceID               0
IP Address             0
MerchantID             0
Channel                0
CustomerAge            0
CustomerOccupation     0
TransactionDuration    0
LoginAttempts          0
AccountBalance         0
dtype: int64

In [ ]:
df['Channel'].unique()

array(['ATM', 'Online', 'Branch'], dtype=object)

# 📊 Pandas: Grouping & Sorting

### 🏗️ 1. Sorting Data
Rearrange your rows based on column values.


| Method | Description |
| :--- | :--- |
| `df.sort_values('col')` | Sort by a column (default: **Ascending**). |
| `df.sort_values('col', ascending=False)` | Sort by a column (Descending). |
| `df.sort_index()` | Sort rows by their **Index** labels. |
| `df.nlargest(5, 'col')` | Quick way to get the **Top 5** highest values. |

---

### 🧱 2. Grouping Data (`groupby`)
The **Split-Apply-Combine** strategy. Use this to calculate metrics per category.

*   **`df.groupby('category').mean()`**: Get averages for every numerical column per group.
*   **`df.groupby('category')['sales'].sum()`**: Sum up a specific column (`sales`) per group.
*   **`df.groupby('category').size()`**: Count the number of rows in each group.
*   **`df[col_name].value_counts()`**: .

---

### 🧪 3. Advanced Aggregation (`agg`)
Use `.agg()` when you need **multiple** statistics at once.

```python
# Get Min, Max, and Mean for the 'Price' column
df.groupby('City')['Price'].agg(['min', 'max', 'mean'])

# Different stats for different columns
df.groupby('Dept').agg({'Salary': 'mean', 'ID': 'count'})

In [ ]:
df.head(3)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91
2,TX000003,AC00019,126.29,7/10/2023 18:16,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35

In [ ]:
df.sort_values('TransactionAmount').head(2)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
43332,TX043333,AC00097,0.24,7/29/2025,Debit,Oklahoma City,D000239,60.197.167.40,M090,Online,20,Student,173,1,1833.67
7325,TX007326,AC00097,0.24,5/3/2023,Debit,Oklahoma City,D000239,60.197.167.40,M090,Online,20,Student,173,1,1833.67

In [ ]:
df.sort_values('TransactionAmount', ascending=False).head(2)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
39962,TX039963,AC00423,2060.59,11/6/2021,Debit,Portland,D000191,207.157.126.125,M033,ATM,30,Doctor,161,1,11090.24
22802,TX022803,AC00179,2026.44,3/30/2021,Credit,Columbus,D000246,141.121.30.32,M012,Online,62,Doctor,83,1,11498.01

In [ ]:
df.sort_values(['TransactionDate', 'TransactionAmount'], ascending=[False, True]).head(5)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
15098,TX015099,AC00111,21.85,9/9/2025,Debit,Denver,D000108,60.43.160.195,M050,ATM,58,Doctor,240,1,11991.24
7198,TX007199,AC00499,47.29,9/9/2025,Debit,Atlanta,D000560,184.4.253.143,M030,Online,21,Student,146,1,842.94
45179,TX045180,AC00296,49.72,9/9/2025,Debit,Dallas,D000645,68.254.244.208,M049,ATM,19,Student,176,1,1503.56
48253,TX048254,AC00131,55.79,9/9/2025,Debit,Detroit,D000217,147.119.62.178,M003,Branch,29,Doctor,76,1,1334.60
34643,TX034644,AC00230,71.59,9/9/2025,Debit,San Jose,D000547,203.174.215.229,M011,Branch,22,Student,49,1,1257.90

In [ ]:
df.nlargest(3, 'TransactionAmount')

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
39962,TX039963,AC00423,2060.59,11/6/2021,Debit,Portland,D000191,207.157.126.125,M033,ATM,30,Doctor,161,1,11090.24
22802,TX022803,AC00179,2026.44,3/30/2021,Credit,Columbus,D000246,141.121.30.32,M012,Online,62,Doctor,83,1,11498.01
16715,TX016716,AC00423,2014.32,7/15/2021,Debit,Portland,D000191,207.157.126.125,M033,ATM,30,Doctor,161,1,11090.24

In [ ]:
df.groupby('TransactionType')['TransactionAmount'].sum()

TransactionType
Credit     3432251.62
Debit     11461359.07
Name: TransactionAmount, dtype: float64

In [ ]:
df.groupby('AccountID').size().sort_values(ascending=False).head(3).reset_index()

  AccountID    0
0   AC00363  249
1   AC00202  241
2   AC00460  238

In [ ]:
df['AccountID'].value_counts().head(3)

AccountID
AC00363    249
AC00202    241
AC00460    238
Name: count, dtype: int64

In [ ]:
df.groupby(['TransactionType', 'AccountID'])['TransactionAmount'].agg(['min', 'max', 'mean']) ## agg can be list or dict with key values

                              min      max        mean
TransactionType AccountID
Credit          AC00002    467.20   560.79  516.613043
                AC00003    390.19   469.85  425.631053
                AC00004     90.49   108.49   99.681500
                AC00005    371.71   481.66  422.927059
                AC00006    151.40   187.44  168.656429
...                           ...      ...         ...
Debit           AC00496     52.60   360.72  188.377794
                AC00497      7.58   351.34  186.964211
                AC00498     25.24  1197.36  467.172857
                AC00499     38.59   901.73  334.245116
                AC00500    121.59   166.83  143.902927

[830 rows x 3 columns]

# 🎯 Pandas: Selecting & Slicing Data

### 📍 1. `loc` vs `iloc`
The two primary ways to "grab" data. Think of **loc** as *location by name* and **iloc** as *integer-location*.


| Method | Selection Type | Logic | Syntax Example |
| :--- | :--- | :--- | :--- |
| **`.loc[]`** | **Label-based** | Uses Row/Column **Names** | `df.loc[0:5, 'Name']` |
| **`.iloc[]`** | **Position-based** | Uses Row/Column **Index (0,1,2...)** | `df.iloc[0:5, 0:2]` |

---

### 🎨 2. Fancy Indexing
Passing a **list** of specific labels or positions to extract exactly what you need.

*   **Specific Rows/Cols**: `df.loc[[1, 5, 10], ['Name', 'Salary']]`
*   **Reordering**: You can use fancy indexing to reorder columns on the fly:  
    `df[['Salary', 'Name', 'ID']]`

---

### 🎭 3. Boolean Masking (Filtering)
Selecting rows based on a condition (the "Excel Filter" equivalent).

```python
# 1. Create a mask (True/False list)
mask = df['Age'] > 25

# 2. Apply it to the dataframe
df[mask]

# Combined shortcut:
df[df['City'] == 'London']

In [ ]:
df.loc[0:3, 'TransactionAmount']

0     14.09
1    376.24
2    126.29
3    184.50
Name: TransactionAmount, dtype: float64

In [ ]:
df.iloc[0:3, 1:3]

  AccountID  TransactionAmount
0   AC00128              14.09
1   AC00455             376.24
2   AC00019             126.29

In [ ]:
df[df['TransactionAmount'] > 300].loc[:,'TransactionAmount'].head(3)

1     376.24
9     815.96
12    494.52
Name: TransactionAmount, dtype: float64

# ✂️ Pandas: Column Management & Duplicates

### 🏗️ 1. Modifying Columns
Change the structure of your DataFrame by removing or renaming fields.


| Operation | Syntax Example | Key Argument |
| :--- | :--- | :--- |
| **Drop Columns** | `df.drop(columns=['Age', 'ID'])` | `inplace=True` to modify original |
| **Drop Rows** | `df.drop(index=[0, 1, 2])` | Removes rows by index labels |
| **Rename** | `df.rename(columns={'old':'new'})` | Takes a dictionary `{old: new}` |
| **Assign** | `df.assign(total=df['a'] + df['b'])` | Create new columns functionally |

---

### 👯 2. Handling Duplicates
Find and remove redundant rows to ensure data integrity.

*   **`df.duplicated()`**: Returns a Boolean Series (`True` if the row is a repeat).
*   **`df.duplicated().sum()`**: Quick way to count how many rows are exact matches.
*   **`df.drop_duplicates()`**: Removes all identical rows, keeping the **first** one by default.

---

### 🧪 3. Advanced Cleanup
Sometimes you only care about duplicates in **specific** columns.

```python
# Check for duplicate IDs only
df.duplicated(subset=['emp_id'])

# Keep the LAST occurrence instead of the first
df.drop_duplicates(subset=['email'], keep='last')

# Rename all columns to lowercase & replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [ ]:
df.drop(columns=['IP Address']).head(2)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,Transaction_int
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,M015,ATM,70,Doctor,81,1,5112.21,14
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,M052,ATM,68,Doctor,141,1,13758.91,376

In [ ]:
df.drop(index=[1]).head(2)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,Transaction_int
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,14
2,TX000003,AC00019,126.29,7/10/2023 18:16,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35,126

In [ ]:
df.rename(columns={'TransactionID': 'transaction_id'}).head(2)

,transaction_id,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,Transaction_int
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,14
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91,376

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates().head(1)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance,Transaction_int
0,TX000001,AC00128,14.09,4/11/2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21,14

# 🔄 Pandas: Reshaping with Melt & Pivot

### 🧊 1. Wide vs. Long Data
*   **Wide Data**: Multiple columns for different categories (e.g., `Jan`, `Feb`, `Mar`). Great for human reading.
*   **Long Data**: One column for "Date" and one for "Value". Great for analysis and plotting.

---

### 🫠 2. `pd.melt()`: Turning Wide to Long
Use this to "unpivot" your data. It turns columns into rows.


| Argument | Description |
| :--- | :--- |
| **`id_vars`** | Columns you want to **keep** (e.g., 'Name'). |
| **`value_vars`** | Columns you want to **unstack** (e.g., 'Jan', 'Feb'). |
| **`var_name`** | New name for the unstacked column header. |
| **`value_name`** | New name for the data values. |

```python
# Example: Convert monthly sales columns into one 'Month' column
df_long = pd.melt(df, id_vars=['Product'], var_name='Month', value_name='Sales')
```

### 📐 3. `df.pivot()`: Turning Long to Wide
The opposite of melt. It turns unique row values into column headers.
index: What stays as your rows (e.g., 'Date').
columns: What becomes your new column headers (e.g., 'City').
values: What fills the cells.

```python
df_wide = df.pivot(index='Date', columns='City', values='Temperature')
```

# 🛠️ Pandas: Datatype Conversion & Parquet Files

### 🔄 1. Datatype Conversion
Converting columns to the correct type is essential for saving memory and enabling specific functions (like date math).


| Method | Best For | Key Feature |
| :--- | :--- | :--- |
| **`.astype()`** | Simple, forced casting | `df['col'].astype('int64')` |
| **`pd.to_numeric()`** | Messy numbers/strings | Use `errors='coerce'` to turn junk into `NaN` |
| **`pd.to_datetime()`** | Dates and Timestamps | Intelligent parsing of multiple date formats |
| **`.astype('category')`** | Low-cardinality strings | Drastically reduces memory for repeated text |

---

### 📦 2. Creating Parquet Files
**Parquet** is a columnar storage format that is much faster and smaller than CSV. It also "remembers" your datatypes!

#### **Basic Save & Load**
```python
# Save to Parquet (Requires 'pyarrow' or 'fastparquet' installed)
# Compression type 'snappy', 'gzip'
df.to_parquet('data.parquet')

# Read from Parquet
df = pd.read_parquet('data.parquet')

In [ ]:
df['TransactionAmount'].dtype

dtype('float64')

In [ ]:
df['Transaction_int'] = df['TransactionAmount'].astype('int64')

In [ ]:
df['Transaction_int'].head(2)

0     14
1    376
Name: Transaction_int, dtype: int64

In [ ]:
df['Transaction_int'].dtype

dtype('int64')

In [ ]:
df['TransactionDate'].dtype

dtype('O')

In [ ]:
dates = pd.to_datetime(df['TransactionDate'], format='mixed').head(5)

In [ ]:
dates.dt.month

0     4
1     6
2     7
3     5
4    10
Name: TransactionDate, dtype: int32

In [ ]:
df.to_parquet('data.parquet')